### ISSUE TITLE
Generated completion no longer works with mpv-git @ 076116a0e

### ISSUE THREAD

**Issue by Coacher** [2ion/mpv-bash-completion#11]
Hello.

I am running Gentoo amd64 with mpv-bash-completion-git @ 25cf58c.
After building mpv-git @ 076116a0e and then rebuilding mpv-bash-completion, the generated completion no longer works, i.e. nothing happens if I hit `<Tab>` after mpv command.
Internal Gentoo QA checks report this:
```
 * Problems with installed bash completions were found:
 *
 *      mpv: does not define any completions (failed to source?).
 *
 * For more details on installing bash-completions, please see:
 * https://wiki.gentoo.org/wiki/Bash/Installing_completion_files
```

This problem is not reproducible with mpv-0.24.0, so something must've changed in mpv causing this.

Please fix.

**Comment by Coacher** [comment]
Generated completion with mpv-0.24.0: https://paste.pound-python.org/show/9h3BByx9j9XxFDa468zQ/
Generated completion with mpv-git @ 076116a0e: https://paste.pound-python.org/show/lA0kqXry6qnPrV83CYIS/

**Comment by Coacher** [comment]
If I manually source the generated completion with mpv-git @ 076116a0e I get:
```
$ source /usr/share/bash-completion/completions/mpv
bash: /usr/share/bash-completion/completions/mpv: line 519: syntax error near unexpected token `)'
bash: /usr/share/bash-completion/completions/mpv: line 519: `)_filedir -d;return;;'
```

**Comment by 2ion** [comment]
Thank you very much for reporting.

There is a small functional change too as explained in the release notes for 3.3.10: https://github.com/2ion/mpv-bash-completion/releases/tag/3.3.10.
