### ISSUE TITLE
Call mpv with `--no-config' option

### ISSUE THREAD

**Issue by Coacher** [2ion/mpv-bash-completion#3]
Hello.

mpv-bash-completion calls `mpv --list-options` to get the list of available options.
When mpv is called without `--no-config` option it creates '~/.config/mpv' directory if one doesn't exist. This is an unintended side effect and can cause access violations when mpv-bash-completion is installed system-wide (usually by root user), e.g. https://bugs.gentoo.org/show_bug.cgi?id=586596

Steps to reproduce:
```
# whoami
root
# ls -la ~/.config/mpv
ls: cannot access /root/.config/mpv: No such file or directory
# mpv --list-options > /dev/null
# ls -la ~/.config/mpv
total 8
drwx------ 2 root root 4096 Jun 22 02:58 ./
drwxr-xr-x 6 root root 4096 Jun 22 02:58 ../
```

`--no-config` option is also used upstream to generate zsh completion: https://github.com/mpv-player/mpv/blob/6f9973618cf7f137f9007d00c86a4949f4b12c71/TOOLS/zsh.pl#L254

Please fix.

**Comment by 2ion** [comment]
Will add the fix tonight to the master and lua-rewrite branches. Thanks for reporting; I wasn't aware of this.

**Comment by Coacher** [comment]
Thank you!
