### ISSUE TITLE
Window sizes are not completed if option is specified with trailing '=', e.g. '--geometry='

### ISSUE THREAD

**Issue by Coacher** [2ion/mpv-bash-completion#7]
Hello.

Window sizes are completed properly if I type `mpv --geometry<Space>` and hit Tab.
But if I type `mpv --geometry=` and hit Tab, sizes aren't completed.
Other options are completed properly with trailing `=`.

Please make window sizes completion work with trailing `=` as well.

**Comment by Coacher** [comment]
This is with mpv-bash-completion-3.3.1.

**Comment by 2ion** [comment]
Fix will be implied by #22 . WONTFIX here.
